services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: askpupkin
      POSTGRES_USER: askpupkin_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: askpupkin
      DB_USER: askpupkin_user
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
